buttonForSelectedDirTitle = "Папка куда будет сохраняться:"
changeLanguage = "Поменять язык"
checkboxOverwriteOutputFilesTitle = "Разрешить перезаписать файл"
choose = "выбрать"
converterVideoFilesSubmitTitle = "Конвертировать"
converterVideoFilesTitle = "Конвертор видео файлов в mp4"
error = "Произошла ошибка!"
errorConverter = "не смогли отконвертировать видео"
errorDatabase = "не смогли создать файл 'database' в папке 'data'"
errorFFmpeg = "это не FFmpeg"
errorFFprobe = "это не FFprobe"
errorSelectedFolderSave = "Не выбрали папку для сохранения!"
exit = "Выход"
fileVideoForConversionTitle = "Файл для ковертации:"
languageSelectionFormHead = "Переключить язык"
languageSelectionHead = "Выберите язык"
pathToFfmpeg = "Путь к ffmpeg:"
pathToFfprobe = "Путь к ffprobe:"
save = "Сохранить"
selectFFPathTitle = "Укажите путь к FFmpeg и к FFprobe"
settings = "Настройки"
titleDownloadLink = "Скачать можно от сюда"
